# -*- coding: utf-8 -*-
"""Light Theme and Dark Theme_A/B Testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsp2y5FL2cVjFW4xcoZSjA3zmXJavZ4W

* Theme: dark or light
* Click Through Rate: The proportion of the users who click on links or buttons on the website.
* Conversion Rate: The percentage of users who signed up on the platform after visiting for the first time.
* Bounce Rate: The percentage of users who leave the website without further interaction after visiting a single page.
* Scroll Depth: The depth to which users scroll through the website pages.
* Age: The age of the user.
* Location: The location of the user.
* Session Duration: The duration of the user’s session on the website.
* Purchases: Whether the user purchased the book (Yes/No).
* Added_to_Cart: Whether the user added books to the cart (Yes/No).
### Which theme yields better user engagement, purchases and conversion rates?
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from statsmodels.stats.proportion import proportions_ztest
from scipy import stats

from google.colab import files
uploaded = files.upload()
import pandas as pd
df = pd.read_csv("website_ab_test.csv")
df.head()

#dataset summary
summary = {
    'Number of Records': df. shape[0],
    'Number of Columns': df.shape[1],
    'Missing Values': df.isnull().sum(),
    'Data Types': df.dtypes,
    'Numerical Columns Summary': df.describe()
}
summary

"""###Summary
* Click Through Rate: Ranges from about 0.01 to 0.50 with a mean of approximately 0.26.
* Conversion Rate: Also ranges from about 0.01 to 0.50 with a mean close to the Click Through Rate, approximately 0.25.
* Bounce Rate: Varies between 0.20 and 0.80, with a mean around 0.51.
* Scroll Depth: Shows a spread from 20.01 to nearly 80, with a mean of 50.32.
Age: The age of users ranges from 18 to 65 years, with a mean age of about 41.5 years.
* Session Duration: This varies widely from 38 seconds to nearly 1800 seconds (30 minutes), with a mean session duration of approximately 925 seconds (about 15 minutes).
"""

# Scatter plot for Click Through Rate and Conversion Rate
fig = px.scatter(df, x='Click Through Rate',
                 y='Conversion Rate', color='Theme',
                 title='CTR vs Conversion Rate', trendline='ols')
fig.show()

"""- The relationship between them is consistent and nearly unchanged
- More users click on links or buttons increases the proportion of them ending up signing up daily
"""

light_theme_data=df[df['Theme']=='Light Theme']
dark_theme_data=df[df['Theme']=='Dark Theme']
fig=go.Figure()
fig.add_trace(go.Histogram(x=light_theme_data['Click Through Rate'], name='Light Theme', opacity=0.6))
fig.add_trace(go.Histogram(x=dark_theme_data['Click Through Rate'], name='Dark Theme', opacity=0.6))
fig.update_layout(
    title_text='Click through Rate by Theme',
    xaxis_title_text='Click Through Rate',
    yaxis_title_text='Frequency',
    barmode='group',
    bargap=0.1
)
fig.show()

"""###Summary
Not a big difference between two themes
"""

fig=go.Figure()
fig.add_trace(go.Histogram(x=light_theme_data['Conversion Rate'], name='Light Theme', opacity=0.6, nbinsx=20))
fig.add_trace(go.Histogram(x=dark_theme_data['Conversion Rate'], name='Dark Theme', opacity=0.6, nbinsx=20))
fig.update_layout(
    title_text='Conversion Rate by Theme',
    xaxis_title_text='Conversion Rate',
    yaxis_title_text='Frequency',
    barmode='group',
    bargap=0.1
)
fig.show()

"""###Summary
There is not much difference, the conversion rate of the dark theme is slightly better than the light theme
"""

fig=go.Figure()
fig.add_trace(go.Box(y=light_theme_data['Bounce Rate'], name='Light Theme'))
fig.add_trace(go.Box(y=dark_theme_data['Bounce Rate'], name='Dark Theme'))
fig.update_layout(
    title_text='Bounce Rate by Theme',
    xaxis_title_text='Bounce Rate',
)
fig.show()

"""###Summary
The bounce rate of Light Theme is slightly better
"""

fig = go.Figure()
fig.add_trace(go.Box(y=light_theme_data['Scroll_Depth'],
                     name='Light Theme'))
fig.add_trace(go.Box(y=dark_theme_data['Scroll_Depth'],
                     name='Dark Theme'))

fig.update_layout(
    title_text='Scroll Depth by Theme',
    yaxis_title_text='Scroll Depth',
)

fig.show()

"""###Summary
The scroll depth of the light theme is slightly better
"""

# A/B testing for Purchases
light_theme_conversions = light_theme_data[light_theme_data['Purchases'] == 'Yes'].shape[0]
light_theme_total = light_theme_data.shape[0]

dark_theme_conversions = dark_theme_data[dark_theme_data['Purchases'] == 'Yes'].shape[0]
dark_theme_total = dark_theme_data.shape[0]

conversion_counts = [light_theme_conversions, dark_theme_conversions]
sample_sizes = [light_theme_total, dark_theme_total]

light_theme_conversion_rate = light_theme_conversions / light_theme_total
dark_theme_conversion_rate = dark_theme_conversions / dark_theme_total

# Perform two-sample proportion test
zstat, pval = proportions_ztest(conversion_counts, sample_sizes)
print("Light Theme Conversion Rate:", light_theme_conversion_rate)
print("Dark Theme Conversion Rate:", dark_theme_conversion_rate)
print("A/B Testing - z-statistic:", zstat, " p-value:", pval)

"""#Summary
- The positive z-statistic value indicates that the conversion rate of the Light Theme is slightly higher than the conversion rate of the Dark Theme.
- The p-value is greater than the typical significance level of 0.05, we do not have enough evidence to reject H0.
> Based on the current data and statistical analysis, there is not enough data to say that one theme performs significantly better than the other in terms of purchases.

"""

light_theme_session_duration = light_theme_data['Session_Duration']
dark_theme_session_duration = dark_theme_data['Session_Duration']

# Calculate the average session duration for both themes
light_theme_avg_duration = light_theme_session_duration.mean()
dark_theme_avg_duration = dark_theme_session_duration.mean()

# Print the average session duration for both themes
print("Light Theme Average Session Duration:", light_theme_avg_duration)
print("Dark Theme Average Session Duration:", dark_theme_avg_duration)

# Perform two-sample t-test for session duration
tstat, pval = stats.ttest_ind(light_theme_session_duration, dark_theme_session_duration)
print("A/B Testing for Session Duration - t-statistic:", tstat, " p-value:", pval)

"""#Summary
- A positive t-statistic value indicates that the average session duration of the Light Theme is slightly higher than the average session duration of the Dark Theme.
- The p-value is greater than the typical significance level of 0.05, we do not have enough evidence to reject H0.
> Results indicate that the average session duration for both themes is similar, and any differences observed may be due to chance.
"""