# -*- coding: utf-8 -*-
"""Light Theme and Dark Theme_Hypothesis Testing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xi9jDXxxY31GhuJwpgF7YCP3--17pXVZ

* Theme: dark or light
* Click Through Rate: The proportion of the users who click on links or buttons on the website.
* Conversion Rate: The percentage of users who signed up on the platform after visiting for the first time.
* Bounce Rate: The percentage of users who leave the website without further interaction after visiting a single page.
* Scroll Depth: The depth to which users scroll through the website pages.
* Age: The age of the user.
* Location: The location of the user.
* Session Duration: The duration of the user’s session on the website.
* Purchases: Whether the user purchased the book (Yes/No).
* Added_to_Cart: Whether the user added books to the cart (Yes/No).
### Which theme yields better user engagement, purchases and conversion rates?
"""

import pandas as pd
from scipy.stats import ttest_ind

from google.colab import files
uploaded = files.upload()
import pandas as pd
df = pd.read_csv("website_ab_test.csv")
df.head()

#dataset summary
summary = {
    'Number of Records': df. shape[0],
    'Number of Columns': df.shape[1],
    'Missing Values': df.isnull().sum(),
    'Numerical Columns Summary': df.describe()
}
summary

"""###Summary
* Click Through Rate: Ranges from about 0.01 to 0.50 with a mean of approximately 0.26.
* Conversion Rate: Also ranges from about 0.01 to 0.50 with a mean close to the Click Through Rate, approximately 0.25.
* Bounce Rate: Varies between 0.20 and 0.80, with a mean around 0.51.
* Scroll Depth: Shows a spread from 20.01 to nearly 80, with a mean of 50.32.
Age: The age of users ranges from 18 to 65 years, with a mean age of about 41.5 years.
* Session Duration: This varies widely from 38 seconds to nearly 1800 seconds (30 minutes), with a mean session duration of approximately 925 seconds (about 15 minutes).
"""

# Step 1: Select only numeric columns
numeric_cols = df.select_dtypes(include='number').columns

# Step 2: Group by "Theme" and compute the mean for numeric columns only
theme_performance = df.groupby("Theme")[numeric_cols].mean()

# Step 3: Sort by "Conversion Rate"
theme_performance_sorted = theme_performance.sort_values(by="Conversion Rate", ascending=False)

print(theme_performance_sorted)

"""* Click Through Rate (CTR): The Dark Theme has a slightly higher average CTR (0.2645) compared to the Light Theme (0.2471).
* Conversion Rate: The Light Theme leads with a marginally higher average Conversion Rate (0.2555) compared to the Dark Theme (0.2513).
* Bounce Rate: The Bounce Rate is slightly higher for the Dark Theme (0.5121) than for the Light Theme (0.4990).
* Scroll Depth: Users on the Light Theme scroll slightly further on average (50.74%) compared to those on the Dark Theme (49.93%).
* Age: The average age of users is similar across themes, with the Light Theme at approximately 41.73 years and the Dark Theme at 41.33 years.
* Session Duration: The average session duration is slightly longer for users on the Light Theme (930.83 seconds) than for those on the Dark Theme (919.48 seconds).
"""

conversion_rate_light=df[df['Theme']=='Light Theme']['Conversion Rate']
conversion_rate_dark=df[df['Theme']=='Dark Theme']['Conversion Rate']
t_stat_con, p_value_con=ttest_ind(conversion_rate_light, conversion_rate_dark, equal_var=False)
t_stat_con, p_value_con

"""p_value =0.65>0.05(significance level)
--> fail to reject H0
"""

click_rate_light=df[df['Theme']=='Light Theme']['Click Through Rate']
click_rate_dark=df[df['Theme']=='Dark Theme']['Click Through Rate']
t_stat_click, p_value_click=ttest_ind(click_rate_light, click_rate_dark, equal_var=False)
t_stat_click, p_value_click

"""p_value=0.048<0.05 --> there is a statistically significant difference"""

bounce_rate_light=df[df['Theme']=='Light Theme']['Bounce Rate']
bounce_rate_dark=df[df['Theme']=='Dark Theme']['Bounce Rate']
t_stat_bounce, p_value_bounce=ttest_ind(bounce_rate_light, bounce_rate_dark, equal_var=False)
t_stat_bounce, p_value_bounce
scroll_depth_light=df[df['Theme']=='Light Theme']['Scroll_Depth']
scroll_depth_dark=df[df['Theme']=='Dark Theme']['Scroll_Depth']
t_stat_scroll, p_value_scroll=ttest_ind(scroll_depth_light, scroll_depth_dark, equal_var=False)
t_stat_scroll, p_value_scroll

comparison_table = pd.DataFrame({
    'Metric': ['Click Through Rate', 'Conversion Rate', 'Bounce Rate', 'Scroll_Depth'],
    'T-Statistic': [t_stat_click, t_stat_con, t_stat_bounce, t_stat_scroll],
    'P-Value': [p_value_click, p_value_con, p_value_bounce, p_value_scroll]
})

comparison_table

"""* Click Through Rate: The test reveals a statistically significant difference, with the Dark Theme likely performing better (P-Value = 0.048).
* Conversion Rate: No statistically significant difference was found (P-Value = 0.635).
* Bounce Rate: There’s no statistically significant difference in Bounce Rates between the themes (P-Value = 0.230).
* Scroll Depth: Similarly, no statistically significant difference is observed in Scroll Depths (P-Value = 0.450).

#Summary
* The two themes perform similarly across most metrics
* The Dark Theme has a slight edge in terms of engaging users to click through.
"""